# Generated by Django 3.2.18 on 2023-02-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название мема')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение мема')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mems', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мем',
                'verbose_name_plural': 'Мемы',
                'ordering': ('-pub_date',),
            },
        ),
    ]
