# Generated by Django 3.2.18 on 2023-02-18 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mems', '0003_alter_mem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mem',
            options={'ordering': ('pub_date',), 'verbose_name': 'Мем', 'verbose_name_plural': 'Мемы'},
        ),
        migrations.AlterField(
            model_name='mem',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.mem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
