# Generated by Django 3.2.18 on 2023-02-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0005_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_or_dislike',
        ),
        migrations.AddField(
            model_name='like',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
