# Generated by Django 3.2.18 on 2023-02-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0007_auto_20230219_1259'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('user', 'mem'), name='unique_for_user_mem'),
        ),
    ]
