# Generated by Django 3.2.18 on 2023-02-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0008_likedislike_unique_for_user_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Продвижение мема'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesdislikes', to='mems.mem', verbose_name='Мем'),
        ),
    ]
