# Generated by Django 3.2.18 on 2023-02-20 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mems', '0009_auto_20230219_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название сообщества')),
                ('description', models.CharField(max_length=1024, unique=True, verbose_name='Описание сообщества')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug сообщества')),
                ('mems', models.ManyToManyField(blank=True, to='mems.Mem')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мемное сообщество',
                'verbose_name_plural': 'Мемные сообщества',
            },
        ),
    ]
