# Generated by Django 3.2.18 on 2023-02-20 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mems', '0010_сommunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сommunity',
            name='mems',
            field=models.ManyToManyField(blank=True, related_name='community', to='mems.Mem'),
        ),
        migrations.AlterField(
            model_name='сommunity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='community', to=settings.AUTH_USER_MODEL),
        ),
    ]
